#!/bin/bash
# epilogue-example - set this on torque_mom's /path/to/mom_priv/epilogue


# Define number of processors.
max_ppn=8

# Define name of provisioning queue
provq="provision"

echo $6 |grep "ppn=$max_ppn" > /dev/null 2>&1
if [ "$8" == "$provq" ]&&[ "$?" = "0" ]; then

    USERNAME=$2
    mom_teefaa=/root/teefaa

    # source    
    source /tmp/userrc

    # Load Teefaa Torque configuration.
    source $mom_teefaa/torque/torquerc

    # Load Teefaa Torque functions.
    source $mom_teefaa/torque/torque_functions

    # Setup userrc and send it to dispather.
    SetSendUserConf

    # Setup Cloud subnet.
    need_subnet=$(cat /tmp/need_subnet 2>/dev/null)
    if [[ "$need_subnet" == "yes" ]]; then
        ResSubnet
    fi
    # Reboot
    reboot

fi

exit 0
