#!/usr/bin/env bash
# localrc is a user maintained settings file that is sourced at the beginning of bootstrap.sh.
# This gives the user's local valuables.

# Define where you mount root partition.
MNT_ROOT=/mnt

# Define logfile.
LOGFILE=/tmp/bootstrap.log

# Define the path to image list.
IMAGE_LIST=$TOP_DIR/image.list

# If you want to setup static IP Addresses and hostnames in the 
# installation process, these ``ADDR_LIST``, ``DIFF_PREFIX`` and ``INTERFACES``
# Need to be difined.
DIFF_TYPE=local
DIFF_DIR=$TOP_DIR/diffs/$DIFF_TYPE/$os_DISTRO/$os_RELEASE

# If ``DIFF_TYPE`` isn't general, these will be needed.
INTERFACES="eth0 eth1 ib0"
GATEWAY="149.165.146.254"
ADDR_LIST=$TOP_DIR/address.list
DIFF_PREFIX="DIFF"

##### Get config from dispatcher #####
